# Generated by Django 5.0.14 on 2026-07-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Asset tag / QR-code identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("CUSTOMER", "Customer-owned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("serial_number", models.CharField(blank=True, max_length=200)),
                ("install_date", models.DateField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=100)),
                ("software_version", models.CharField(blank=True, max_length=100)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INSTALLED", "Installed"),
                            ("ACTIVE", "Active"),
                            ("IN_MAINTENANCE", "In maintenance"),
                            ("DECOMMISSIONED", "Decommissioned"),
                        ],
                        default="INSTALLED",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_label",
                    models.CharField(
                        help_text='e.g. "v3" or a date-based label', max_length=50
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Since when this version applies, shown to users at a glance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="assets.configurationtemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetConfigurationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuration_assignments",
                        to="assets.asset",
                    ),
                ),
                (
                    "configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_assignments",
                        to="assets.configurationversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="assets.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="customer_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.customersite",
            ),
        ),
        migrations.CreateModel(
            name="ConfigurationVersionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.configurationversion",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assets.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("configuration_version", "item")},
            },
        ),
        migrations.AddField(
            model_name="configurationversion",
            name="items",
            field=models.ManyToManyField(
                through="assets.ConfigurationVersionItem", to="assets.item"
            ),
        ),
        migrations.CreateModel(
            name="ServiceContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("sla_description", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="assets.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="service_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.servicecontract",
            ),
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="spare_parts", to="assets.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terminals",
                        to="assets.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "code")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.terminal",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("customer_site__isnull", True),
                        ("ownership", "INTERNAL"),
                        ("terminal__isnull", False),
                    ),
                    models.Q(
                        ("customer_site__isnull", False),
                        ("ownership", "CUSTOMER"),
                        ("terminal__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="asset_ownership_location_consistency",
            ),
        ),
    ]
