# Generated by Django 5.0.14 on 2026-07-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
