# Generated by Django 5.0.14 on 2026-07-15 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_sparepart_barcode"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_sites", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_sites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
