# Generated by Django 5.0.14 on 2026-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_site_allowed_groups_site_allowed_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Used for parts cost reporting",
                max_digits=10,
                null=True,
            ),
        ),
    ]
