# Generated by Django 5.0.14 on 2026-07-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_sparepart_unit_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecontract",
            name="sla_resolution_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Target hours from ticket creation to close",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="sla_response_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Target hours from ticket creation to work starting",
                null=True,
            ),
        ),
    ]
