# Generated by Django 5.0.14 on 2026-07-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_servicecontract_sla_resolution_hours_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asset",
            name="asset_ownership_location_consistency",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="ownership",
        ),
        migrations.AddField(
            model_name="asset",
            name="owner_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_assets",
                to="assets.customer",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="customer_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.customersite",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="terminal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.terminal",
            ),
        ),
    ]
