# Generated by Django 5.0.14 on 2026-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_vendor_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
