# Generated by Django 5.0.14 on 2026-07-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("workorders", "0002_workorder_actual_close_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Checklist / procedure notes for the generated work order",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(help_text="Repeat every N days"),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Anchor date the recurrence is calculated from"
                    ),
                ),
                ("next_due_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Pause without deleting"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pm_schedules",
                        to="assets.asset",
                    ),
                ),
                (
                    "last_generated_work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workorders.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PMScheduleGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date_at_generation", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pm_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generations",
                        to="maintenance.pmschedule",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pm_generation",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
