# Generated by Django 5.0.14 on 2026-07-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_seed_pm_periodic_task"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pmschedule",
            name="assigned_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_schedules",
                to="teams.team",
            ),
        ),
    ]
