# Generated by Django 5.0.14 on 2026-07-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_checklist_permissions"),
        ("maintenance", "0003_pmschedule_assigned_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="pmschedule",
            name="checklist_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_schedules",
                to="core.checklisttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="pmschedule",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Free-text procedure notes for the generated work order",
            ),
        ),
    ]
