# Generated by Django 5.0.14 on 2026-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_pmschedule_checklist_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pmschedule",
            name="meter_interval",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Repeat every N meter units (hours or cycles) - requires meter_type",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pmschedule",
            name="meter_type",
            field=models.CharField(
                blank=True,
                choices=[("HOURS", "Running hours"), ("CYCLES", "Cycles")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pmschedule",
            name="next_due_meter_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
