# Generated by Django 5.0.14 on 2026-07-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_checklist_permissions"),
        ("safety", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permittowork",
            name="checklist_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permits_to_work",
                to="core.checklisttemplate",
            ),
        ),
    ]
