# Generated by Django 5.0.14 on 2026-07-15 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0002_permittowork_checklist_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permittowork",
            options={
                "permissions": [
                    ("can_approve_permittowork", "Can approve permit to work")
                ]
            },
        ),
        migrations.AddField(
            model_name="permittowork",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permittowork",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_permits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
