# Generated by Django 5.0.14 on 2026-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="actual_close_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="actual_open_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="cause",
            field=models.TextField(blank=True, help_text="Root cause, once known"),
        ),
        migrations.AddField(
            model_name="workorder",
            name="resolution",
            field=models.TextField(blank=True, help_text="How it was resolved"),
        ),
        migrations.AddField(
            model_name="workorder",
            name="symptoms",
            field=models.TextField(blank=True, help_text="What was observed"),
        ),
    ]
