# Generated by Django 5.0.14 on 2026-07-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("workorders", "0002_workorder_actual_close_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderpartusage",
            name="stock_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="part_usages",
                to="inventory.stocklocation",
            ),
        ),
    ]
