# Generated by Django 5.0.14 on 2026-07-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("workorders", "0003_workorderpartusage_stock_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="assigned_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="teams.team",
            ),
        ),
    ]
