# Generated by Django 5.0.14 on 2026-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0004_workorder_assigned_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="scheduled_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
