# Generated by Django 5.0.14 on 2026-07-15 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_checklist_permissions"),
        ("workorders", "0007_workordercomment_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="checklist_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="core.checklisttemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderChecklistResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_text",
                    models.CharField(
                        help_text="PASS/FAIL, a number, or free text, depending on the item's response_type",
                        max_length=300,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.checklistitem",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_responses",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["completed_at"],
            },
        ),
    ]
