# Generated by Django 5.0.14 on 2026-07-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0009_workorderchecklistresponse_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderlaborentry",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
