# Generated by Django 5.0.14 on 2026-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0010_workorderlaborentry_hourly_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In progress"),
                    ("WAITING_ON_PARTS", "Waiting on parts"),
                    ("ON_HOLD", "On hold"),
                    ("COMPLETED", "Completed"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
