# Generated by Django 5.0.14 on 2026-07-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "LOTO Authorized", "Confined Space Entry", "Forklift"',
                        max_length=200,
                    ),
                ),
                ("issued_date", models.DateField()),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if this certification doesn't expire",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
